import path from "path"
import { fileURLToPath } from "url"

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const dir = path.resolve(__dirname, "..")

process.chdir(dir)

const snapshotPath = path.join(dir, "src/provider/models-snapshot.js")
const dtsPath = path.join(dir, "src/provider/models-snapshot.d.ts")
const modelsUrl = process.env.AM_MODELS_URL || "https://models.dev"
const CACHE_TTL_MS = 24 * 60 * 60 * 1000 // 24 hours

const writeSnapshot = (data: string) =>
  Promise.all([
    Bun.write(
      snapshotPath,
      `// @ts-nocheck\n// Auto-generated by build.ts - do not edit\nexport const snapshot = ${data}\n`,
    ),
    Bun.write(
      dtsPath,
      `// Auto-generated by build.ts - do not edit\nexport declare const snapshot: Record<string, unknown>\n`,
    ),
  ])

// Check if a fresh cached snapshot already exists
const snapshotFile = Bun.file(snapshotPath)
const snapshotExists = await snapshotFile.exists()
if (snapshotExists) {
  const stat = await snapshotFile.stat()
  const age = Date.now() - stat.mtime.getTime()
  if (age < CACHE_TTL_MS) {
    console.log("Models snapshot is fresh (< 24h old), skipping fetch")
    process.exit(0)
  }
}

// Fetch and generate models.dev snapshot
let modelsData: string | undefined
if (process.env.MODELS_DEV_API_JSON) {
  modelsData = await Bun.file(process.env.MODELS_DEV_API_JSON).text()
  await writeSnapshot(modelsData)
} else {
  try {
    modelsData = await fetch(`${modelsUrl}/api.json`).then((x) => x.text())
    await writeSnapshot(modelsData)
  } catch {
    if (snapshotExists) {
      console.log("Failed to fetch models.dev, keeping existing cached snapshot")
      process.exit(0)
    }
    throw error
  }
}

console.log("Generated models-snapshot.js")
