import { Config } from "effect"

function truthy(key: string) {
  const value = process.env[key]?.toLowerCase()
  return value === "true" || value === "1"
}

function falsy(key: string) {
  const value = process.env[key]?.toLowerCase()
  return value === "false" || value === "0"
}

function number(key: string) {
  const value = process.env[key]
  if (!value) return undefined
  const parsed = Number(value)
  return Number.isInteger(parsed) && parsed > 0 ? parsed : undefined
}

const AM_EXPERIMENTAL = truthy("AM_EXPERIMENTAL")
const AM_DISABLE_CLAUDE_CODE = truthy("AM_DISABLE_CLAUDE_CODE")
const AM_DISABLE_CLAUDE_CODE_SKILLS =
  AM_DISABLE_CLAUDE_CODE || truthy("AM_DISABLE_CLAUDE_CODE_SKILLS")
const copy = process.env["AM_EXPERIMENTAL_DISABLE_COPY_ON_SELECT"]

export const Flag = {
  OTEL_EXPORTER_OTLP_ENDPOINT: process.env["OTEL_EXPORTER_OTLP_ENDPOINT"],
  OTEL_EXPORTER_OTLP_HEADERS: process.env["OTEL_EXPORTER_OTLP_HEADERS"],

  AM_AUTO_SHARE: truthy("AM_AUTO_SHARE"),
  AM_AUTO_HEAP_SNAPSHOT: truthy("AM_AUTO_HEAP_SNAPSHOT"),
  AM_GIT_BASH_PATH: process.env["AM_GIT_BASH_PATH"],
  AM_CONFIG: process.env["AM_CONFIG"],
  AM_CONFIG_CONTENT: process.env["AM_CONFIG_CONTENT"],
  AM_DISABLE_AUTOUPDATE: truthy("AM_DISABLE_AUTOUPDATE"),
  AM_ALWAYS_NOTIFY_UPDATE: truthy("AM_ALWAYS_NOTIFY_UPDATE"),
  AM_DISABLE_PRUNE: truthy("AM_DISABLE_PRUNE"),
  AM_DISABLE_TERMINAL_TITLE: truthy("AM_DISABLE_TERMINAL_TITLE"),
  AM_SHOW_TTFD: truthy("AM_SHOW_TTFD"),
  AM_PERMISSION: process.env["AM_PERMISSION"],
  AM_DISABLE_DEFAULT_PLUGINS: truthy("AM_DISABLE_DEFAULT_PLUGINS"),
  AM_DISABLE_LSP_DOWNLOAD: truthy("AM_DISABLE_LSP_DOWNLOAD"),
  AM_ENABLE_EXPERIMENTAL_MODELS: truthy("AM_ENABLE_EXPERIMENTAL_MODELS"),
  AM_DISABLE_AUTOCOMPACT: truthy("AM_DISABLE_AUTOCOMPACT"),
  AM_DISABLE_MODELS_FETCH: truthy("AM_DISABLE_MODELS_FETCH"),
  AM_DISABLE_MOUSE: truthy("AM_DISABLE_MOUSE"),
  AM_DISABLE_CLAUDE_CODE,
  AM_DISABLE_CLAUDE_CODE_PROMPT: AM_DISABLE_CLAUDE_CODE || truthy("AM_DISABLE_CLAUDE_CODE_PROMPT"),
  AM_DISABLE_CLAUDE_CODE_SKILLS,
  AM_DISABLE_EXTERNAL_SKILLS: truthy("AM_DISABLE_EXTERNAL_SKILLS"),
  AM_FAKE_VCS: process.env["AM_FAKE_VCS"],
  AM_SERVER_PASSWORD: process.env["AM_SERVER_PASSWORD"],
  AM_SERVER_USERNAME: process.env["AM_SERVER_USERNAME"],
  AM_ENABLE_QUESTION_TOOL: truthy("AM_ENABLE_QUESTION_TOOL"),

  // Experimental
  AM_EXPERIMENTAL,
  AM_EXPERIMENTAL_FILEWATCHER: Config.boolean("AM_EXPERIMENTAL_FILEWATCHER").pipe(
    Config.withDefault(false),
  ),
  AM_EXPERIMENTAL_DISABLE_FILEWATCHER: Config.boolean("AM_EXPERIMENTAL_DISABLE_FILEWATCHER").pipe(
    Config.withDefault(false),
  ),
  AM_EXPERIMENTAL_ICON_DISCOVERY: AM_EXPERIMENTAL || truthy("AM_EXPERIMENTAL_ICON_DISCOVERY"),
  AM_EXPERIMENTAL_DISABLE_COPY_ON_SELECT:
    copy === undefined ? process.platform === "win32" : truthy("AM_EXPERIMENTAL_DISABLE_COPY_ON_SELECT"),
  AM_ENABLE_EXA: truthy("AM_ENABLE_EXA") || AM_EXPERIMENTAL || truthy("AM_EXPERIMENTAL_EXA"),
  AM_EXPERIMENTAL_BASH_DEFAULT_TIMEOUT_MS: number("AM_EXPERIMENTAL_BASH_DEFAULT_TIMEOUT_MS"),
  AM_EXPERIMENTAL_OUTPUT_TOKEN_MAX: number("AM_EXPERIMENTAL_OUTPUT_TOKEN_MAX"),
  AM_EXPERIMENTAL_OXFMT: AM_EXPERIMENTAL || truthy("AM_EXPERIMENTAL_OXFMT"),
  AM_EXPERIMENTAL_LSP_TY: truthy("AM_EXPERIMENTAL_LSP_TY"),
  AM_EXPERIMENTAL_LSP_TOOL: AM_EXPERIMENTAL || truthy("AM_EXPERIMENTAL_LSP_TOOL"),
  AM_EXPERIMENTAL_PLAN_MODE: AM_EXPERIMENTAL || truthy("AM_EXPERIMENTAL_PLAN_MODE"),
  AM_EXPERIMENTAL_SCOUT: AM_EXPERIMENTAL || truthy("AM_EXPERIMENTAL_SCOUT"),
  AM_EXPERIMENTAL_MARKDOWN: !falsy("AM_EXPERIMENTAL_MARKDOWN"),
  AM_ENABLE_PARALLEL: truthy("AM_ENABLE_PARALLEL") || truthy("AM_EXPERIMENTAL_PARALLEL"),
  AM_MODELS_URL: process.env["AM_MODELS_URL"],
  AM_MODELS_PATH: process.env["AM_MODELS_PATH"],
  AM_DISABLE_EMBEDDED_WEB_UI: truthy("AM_DISABLE_EMBEDDED_WEB_UI"),
  AM_DB: process.env["AM_DB"],
  AM_DISABLE_CHANNEL_DB: truthy("AM_DISABLE_CHANNEL_DB"),
  AM_SKIP_MIGRATIONS: truthy("AM_SKIP_MIGRATIONS"),
  AM_STRICT_CONFIG_DEPS: truthy("AM_STRICT_CONFIG_DEPS"),

  AM_WORKSPACE_ID: process.env["AM_WORKSPACE_ID"],
  AM_EXPERIMENTAL_WORKSPACES: AM_EXPERIMENTAL || truthy("AM_EXPERIMENTAL_WORKSPACES"),
  AM_EXPERIMENTAL_EVENT_SYSTEM: AM_EXPERIMENTAL || truthy("AM_EXPERIMENTAL_EVENT_SYSTEM"),
  AM_EXPERIMENTAL_SESSION_SWITCHING: AM_EXPERIMENTAL || truthy("AM_EXPERIMENTAL_SESSION_SWITCHING"),

  // Evaluated at access time (not module load) because tests, the CLI, and
  // external tooling set these env vars at runtime.
  get AM_DISABLE_PROJECT_CONFIG() {
    return truthy("AM_DISABLE_PROJECT_CONFIG")
  },
  get AM_TUI_CONFIG() {
    return process.env["AM_TUI_CONFIG"]
  },
  get AM_CONFIG_DIR() {
    return process.env["AM_CONFIG_DIR"]
  },
  get AM_PURE() {
    return truthy("AM_PURE")
  },
  get AM_PLUGIN_META_FILE() {
    return process.env["AM_PLUGIN_META_FILE"]
  },
  get AM_CLIENT() {
    return process.env["AM_CLIENT"] ?? "cli"
  },
}
